name: ft_cli
description: This project is one CLI for integrate Flutter and Dart with Clean Architecture
version: 0.1.8+10
homepage: https://github.com/jheimes-silveira/ft_cli

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  path: ^1.8.3
  args: ^2.3.2
  get_it: ^7.2.0
  ansicolor: ^2.0.1
  recase: ^4.1.0
  process_run: ^0.12.5+2
  interact: ^2.1.1

dev_dependencies:
  test: ^1.22.2
  flutter_lints: ^2.0.1
executables:
  ft_cli: ft_cli
