name: js_cli
description: This project is one CLI for integrate Flutter and Dart with Clean Architecture
version: 0.0.1


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  args: ^2.1.0
  get_it: ^7.1.3
  ansicolor: ^2.0.1
  recase: ^4.0.0
  process_run: ^0.12.1
  cli_dialog: ^0.5.0

dev_dependencies:
  test: ^1.16.5

executables:
  js_cli: js_cli
